### PR TITLE
Support AWS Provider V5

### PR DESCRIPTION
**Pull request by max-lobur**
## what

Support AWS Provider V5
Bump codepipeline GitHub provider to 2
Linter fixes

## why

Maintenance

## references

https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.0.0

### CODE REVIEW

**Comment by mihaiplesa** [comment]
@max-lobur this should be great to update too. Many thanks!

**Comment by max-lobur** [comment]
CodeBuild has landed. This one will require codestar refactoring to complete https://docs.aws.amazon.com/codepipeline/latest/userguide/action-reference-CodestarConnectionSource.html#action-reference-CodestarConnectionSource-example

**Comment by mihaiplesa** [comment]
@max-lobur thank you so much for the progress so far. Almost there.

**Pull request closed without merging**
