### PR TITLE
Fix failing test

### PR DESCRIPTION
**Pull request by drselump14**
## what

Fix the failing test because outdated code

## why

Test is failing on most of pull request

### CODE REVIEW

**Comment by drselump14** [comment]
update the readme

**Comment by hans-d** [comment]
Likely failing tesrratest due to some of the ancient versions involved.
@drselump14 can you see if you can get some decent versions here? I wont be able to process that bit, but this issue in general has my attention and working on a cross-repo fix re how we call the tests and can run them more easily locally.

**Comment by drselump14** [comment]
@hans-d I updated the terraform versions to follow the versions on https://github.com/cloudposse/terraform-aws-vpc/blob/main/versions.tf 

I only checked if `terraform apply` works on the examples folder. Not really sure how to invoke the test script as it's always failed with different errors on local

**Comment by hans-d** [comment]
> Not really sure how to invoke the test script as it's always failed with different errors on local
no worries, we try to make that simpler (and better documented) as well.

**Comment by hans-d** [comment]
@drselump14 Hi, can you update the this https://github.com/cloudposse/terraform-aws-ecs-codepipeline/blob/24ea7355a2cd3763df47415d11f82da3f11bcf16/examples/complete/versions.tf#L2 so that it want TF >= 1?

That should resolve the test from failing. (and we need a new readme)

**Comment by drselump14** [comment]
> @drselump14 Hi, can you update the this
> 
> https://github.com/cloudposse/terraform-aws-ecs-codepipeline/blob/24ea7355a2cd3763df47415d11f82da3f11bcf16/examples/complete/versions.tf#L2
> so that it want TF >= 1?
> 
> That should resolve the test from failing. (and we need a new readme)

Done ✅

**Review by hans-d — DISMISSED** [review]

**Comment by kevcube** [comment]
@drselump14 still failing, the error is a go error. I think possibly one output is not formatted as expected? I'll dig in later today.

**Comment by Roondel** [comment]
> @drselump14 still failing, the error is a go error. I think possibly one output is not formatted as expected? I'll dig in later today.

@kevcube where you able to dig into this at all? I am fighting the same error on PR #121 

what I saw when I tried to trigger the test locally using go cli was an error for unmarshalling the json:
FAIL: TestExamplesComplete (366.65s)
test_examples_complete_test.go:42:
Error Trace: test_examples_complete_test.go:42
Error: Received unexpected error:
json: cannot unmarshal string into Go value of type map[string]interface {}
Test: TestExamplesComplete
test_examples_complete_test.go:43:
Error Trace: test_examples_complete_test.go:43
Error: Not equal:
expected: string("geodesic")
actual : ()
Test: TestExamplesComplete
test_examples_complete_test.go:44:
Error Trace: test_examples_complete_test.go:44
Error: Not equal:
expected: string("cloudposse/geodesic")
actual : ()
Test: TestExamplesComplete
panic: interface conversion: interface {} is nil, not float64 [recovered]
panic: interface conversion: interface {} is nil, not float64

**Comment by kevcube** [comment]
@Roondel I think terratest needs to be upgraded in this repo. I will try that now

**Review by kevcube — APPROVED** [review]

**Comment by kevcube** [comment]
removing `no-release` tag because we are updating a dependency

**Review by gberenice — APPROVED** [review]
:shipit: 🚀

**Pull request merged**
