### PR TITLE
Add build_type

### LINKED ISSUE #86: Support build_type parameter
## Describe the Feature

Specify `ARM_CONTAINER` for `environment.type` of `aws_codebuild_project` resource.
Of course CodeBuild is wrapped with cloudposse/terraform-aws-codebuild, and it accepts this value as `build_type` variable.

## Expected Behavior

`build_type` parameter is supported that is to be passed to cloudposse/terraform-aws-codebuild module.
https://github.com/cloudposse/terraform-aws-codebuild/blob/master/main.tf#L343

## Use Case

I want to run CodeBuild on Graviton2.

## Describe Ideal Solution

Add a parameter.

## Alternatives Considered

N/A

## Additional Context

N/A

### PR DESCRIPTION
**Pull request by drselump14**
## what
* Add build_type as codebuild option

## why
* `build_type` is required to utilize arm container

## references
* close #86

### CODE REVIEW

**Comment by hans-d** [comment]
@drselump14 Hi, can you update the pr so that it passes the tests? otherwise, it is likely to be closed due to staleness.

**Comment by drselump14** [comment]
@hans-d Hi, I've rebased the branch with the master branch

**Comment by hans-d** [comment]
@drselump14 if you can take care of the failing readme test as well?
```
README.md is outdated. Please run the following commands locally and push the file:
  make init
  make readme
Error: Process completed with exit code 1.
```

**Review by hans-d — APPROVED** [review]

**Pull request closed without merging**
