### PR TITLE
bugfix: updating codebuild to latest version. 2.0.1

### PR DESCRIPTION
**Pull request by Roondel**
## what

the module version being used for the codebuild module call has been updated from 1.0.0 to 2.0.1. 

## why

this module was broken and throwing an error due to a dynamic auth block that has been removed in the latest codebuild module.

## references

closes issue #120 
https://github.com/cloudposse/terraform-aws-ecs-codepipeline/issues/120
#115

### CODE REVIEW

**Comment by joe-niland** [comment]
Hi @Roondel 
thanks for this and sorry for the delay in reviewing.
I think we'll need to bump the min Terraform version to 1.3 in this project too, to match the Codebuild module.
This would need to be done for `versions.tf` and `examples/complete/versions.tf`

Once that's done, please run:

```
make init
make github/init
make readme
```

**Comment by Roondel** [comment]
Hi Joe, the failed terratest was for an outdated VPC module dependency. I have attempted to bump this VPC module version in codepipeline, VPC module has required terraform provider:
 terraform {
  required_version = ">= 1.0.0"


 "module subnets" also uses this VPC module, granted a much more recent version.
 required terraform provider for subnets module:
 terraform {
  required_version = ">= 1.1.0"
  
The others I have bumped have no breaking changes. Do these terraform providers within VPC and dynamic subnets need to be flush with codepipeline and codebuild i.e. >=1.3.0?
If so, I can raise PR's for these projects, I would really love to get this one back up and running.

**Comment by joe-niland** [comment]
Thanks @Roondel 

The main error now is:

```
TestExamplesComplete 2024-02-22T02:19:20Z command.go:121: │ Error: Invalid value for input variable
TestExamplesComplete 2024-02-22T02:19:20Z command.go:121: │ 
TestExamplesComplete 2024-02-22T02:19:20Z command.go:121: │   on main.tf line 17, in module "subnets":
TestExamplesComplete 2024-02-22T02:19:20Z command.go:121: │   17:   igw_id               = module.vpc.igw_id
TestExamplesComplete 2024-02-22T02:19:20Z command.go:121: │ 
TestExamplesComplete 2024-02-22T02:19:20Z command.go:121: │ The given value is not suitable for module.subnets.var.igw_id declared at
TestExamplesComplete 2024-02-22T02:19:20Z command.go:121: │ .terraform/modules/subnets/variables.tf:6,1-18: list of string required.
```

Also please run `terraform fmt` in `examples/complete/`

**Comment by joe-niland** [comment]
@Roondel looks like the tests need a bit of an update. Let me know if you need me to look at that.

**Pull request closed without merging**
