### PR TITLE
[BREAKING CHANGE] support type attribute for CodeBuild environment vars

### PR DESCRIPTION
**Pull request by joe-niland**
## what
* [BREAKING CHANGE] modify environment_variables variable to support the 'type' key

## why
* The CodeBuild module used by this one now supports the 'type' attribute
* Adding the 'type' attribute allows sourcing env vars from SSM Parameter Store and Secrets Manager

## references
* None

### CODE REVIEW

**Comment by joe-niland** [comment]
@Gowiem this is a complementary PR to https://github.com/cloudposse/terraform-aws-codebuild/pull/88

**Review by Gowiem — APPROVED** [review]

**Pull request merged**
