### PR TITLE
Add bitbucket support

### PR DESCRIPTION
**Pull request by joe-niland**
I needed to add Bitbucket support for CodePipeline so this is my attempt.
I'm not sure if you want to add it since you may only want to support GitHub.

For now I also duplicated the CodePipeline resource block but I think it could be done with a single block and dynamic.

Let me know your thoughts.

### CODE REVIEW

**Comment by osterman** [comment]
@joe-niland looks like we have some merge conflicts

**Comment by joe-niland** [comment]
@osterman this should be OK now. I'm not sure if I agree with defaulting the cache to S3 but I left it in from upstream.

I ran the tests locally but got stuck on the terraform-docs ones. Is there a guide/doc about testing? I didn't get the time to dig into it yet.

**Comment by jamengual** [comment]
> @osterman this should be OK now. I'm not sure if I agree with defaulting the cache to S3 but I left it in from upstream.
> 
> I ran the tests locally but got stuck on the terraform-docs ones. Is there a guide/doc about testing? I didn't get the time to dig into it yet.

If not set to S3 many of our other modules will fail the test, that is why it defaults to S3.
The variable is exposed so it should be no problem for you to change it

**Comment by joe-niland** [comment]
> > @osterman this should be OK now. I'm not sure if I agree with defaulting the cache to S3 but I left it in from upstream.
> > 
> > I ran the tests locally but got stuck on the terraform-docs ones. Is there a guide/doc about testing? I didn't get the time to dig into it yet.
> 
> If not set to S3 many of our other modules will fail the tests, that is why it defaults to S3.
> 
> 
> 

@jamengual thanks for explaining

**Pull request merged**
