### PR TITLE
Clarifying GitHub OAuth token variable

### PR DESCRIPTION
**Pull request by justnom**
## what
Clarifying what the `github_oauth_token` variable should contain.

## why
The `aws-codebuild` module changed the default type for the `github_token` variable to `PARAMTER_STORE` from `PLAINTEXT` in this commit https://github.com/cloudposse/terraform-aws-codebuild/commit/d0782827c25de91f41b7ea2421ef4970f047f3be.

### CODE REVIEW

**Comment by jamengual** [comment]
@justnom you need to run : 
`make init`
`make readme`

then changes need to be made in the README.yaml, not on the .md file, the README.dm is autogenerated from the yaml version.
and then commit that to fix the readme.

**Comment by Gowiem** [comment]
@justnom Thoughts on updating regarding the above? Or do you want to just ship this how it is? No worries if you want to just get this done and shipped -- We can do that and track an issue for another contributor.

**Review by nitrocode — APPROVED** [review]

**Comment by Gowiem** [comment]
@justnom friendly ping on this PR, my above comment, and https://github.com/cloudposse/terraform-aws-ecs-web-app/pull/175. This is a legitimate change and we want to get it in, but need your help now that we've let it drag a bit!

**Pull request closed without merging**
